routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MessageController@index')->name('messages');


Route::resource('messages', 'MessageController')->except(['create']);

app/Message.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Message extends Model
{
    //
    public function getCreatedAtAttribute($date)
    {
        return Carbon::createFromFormat('Y-m-d H:i:s',
            $date)->format("H-i-s/d.m.Y");
    }

    public function getUpdatedAtAttribute($date)
    {
        return Carbon::createFromFormat('Y-m-d H:i:s',
            $date)->format("H-i-s/d.m.Y");
    }
}

resources/views/edit.blade.php
@extends('_layouts._layout')

@section('form')
    <a href="{{ route('messages') }}">Вернуться к просмотру всех сообщений</a>

    <form action="{{ route('messages.update', $message->id) }}" method="POST" id="formid" class="border border-left-0 border-right-0 py-4 my-4">

        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif


        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="name">Имя: *</label>
            <input class="form-control" placeholder="Имя" name="name" value="{{ old('name') ?? $message->name }}" type="text" id="name">
        </div>

        <div class="form-group">
            <label for="message">Сообщение: *</label>
            <textarea class="form-control" rows="5" placeholder="Тект сообщения" name="message" cols="50" id="message">{{ old('message') ?? $message->message }}</textarea>
        </div>

        <div class="form-group">
            <input class="btn btn-primary" type="submit" value="Обновить"/>
        </div>
    </form>
@endsection



@section('jQueryInline')
    <script type="text/javascript">
        // #formid
        $(window).on("beforeunload", function () {
            return "Are you sure? You didn't finish the form!";
        });
        $(document).ready(function () {
            $("#formid").on("submit", function (e) {
                //check form to make sure it is kosher
                //remove the ev
                $(window).off("beforeunload");
                return true;
            });
        });
    </script>
@endsection

resources/views/index.blade.php
@extends('_layouts._layout')

@section('form')
    <form action="{{ route('messages.store') }}" method="POST" id="id-form_messages"
          class="border border-left-0 border-right-0 py-4 my-4">

        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        @if (session('sessionMessage'))
            <div class="alert alert-success" role="alert">
                {{ session('sessionMessage') }}
            </div>
        @endif


        @csrf
        {{-- @method('PUT') --}}
        <div class="form-group">
            <label for="name">Имя: *</label>
            <input class="form-control" placeholder="Имя" name="name" value="{{ old('name') }}" type="text" id="name">
        </div>

        <div class="form-group">
            <label for="message">Сообщение: *</label>
            <textarea class="form-control" rows="5" placeholder="Тект сообщения" name="message" cols="50"
                      id="message">{{ old('message') }}</textarea>
        </div>

        <div class="form-group">
            <input class="btn btn-primary" type="submit" value="Добавить"/>
        </div>
    </form>
@endsection


@section('messages_count')
    <div class="text-right mb-4"><b>Всего сообщений:</b> <i class="badge badge-secondary">{{ $countOfMessages }}</i>
    </div>
@endsection


@section('messages_section')
    <section class="messages mb-4">

        @foreach ($allMessages as $oneMessage)
            <a name='{{ $oneMessage->id }}'></a>
            <div class="card mb-4">
                <div class="card-header">
                    <div class="row">
                        <div class="col">
                            <a href="{{ route('messages.show', $oneMessage->id) }}">
                                #{{ $oneMessage->id }} {{ $oneMessage->name }}
                            </a>
                        </div>
                        <div
                            class="col text-right label label-info">{{ $oneMessage->created_at }}<!-- 17:11:11 / 01.02.2001 --></div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-10 col-lg-11 border border-left-0 border-bottom-0 border-top-0">
                            {{ $oneMessage->message }}
                        </div>
                        <div class="col-2 col-lg-1 text-center">
                            <a class="btn btn-info mb-3" href="{{ route('messages.edit', $oneMessage->id) }}">
                                <i class="fas fa-pencil-alt"></i>
                            </a>

                            @include('_parts._deleteButtonConfirmation', array('message' => $oneMessage))

                        </div>
                    </div>
                </div>
            </div>
        @endforeach

        {{ $allMessages->render() }}

    </section>
@endsection

resources/views/show.blade.php
@extends('_layouts._layout')


@section('content')
    @if (session('sessionMessage'))
        <div class="alert alert-success" role="alert">
            {{ session('sessionMessage') }}
        </div>
    @endif


    <a href="{{ route('messages') }}">Вернуться к просмотру всех сообщений</a>


    <div class="card my-5">
        <div class="card-header">
            <div class="row">
                <div class="col">Сообщение от <strong>{{ $message->name }}</strong></div>
                <div class="col text-right">№ сообщения: {{ $message->id }}</div>
            </div>
        </div>
        <div class="card-body">
            <h5 class="card-title">Текст сообщения:</h5>
            <p class="card-text border border-left-0 border-right-0 border-top-0 mb-3 pb-3">{{ $message->message }}</p>

            <div class="text-center">
                @if ($previusID != NULL)
                    <a class="btn btn-info mx-1" href="{{ route('messages.show', $previusID) }}"
                       title="предыдущее сообщение">
                        <i class="fas fa-arrow-left"></i>
                    </a>
                @endif

                <a class="btn btn-info mx-1" href="{{ route('messages.edit', $message->id) }}">
                    <i class="fas fa-pencil-alt"></i>
                </a>

                @include('_parts._deleteButtonConfirmation')

                @if ($nextID != NULL)
                    <a class="btn btn-info mx-1" href="{{ route('messages.show', $nextID) }}"
                       title="следующее сообщение">
                        <i class="fas fa-arrow-right"></i>
                    </a>
                @endif
            </div>
        </div>
        <div class="card-footer">
            <div class="row">
                <div class="col label label-info">Создано: {{ $message->created_at }}</div>
                <div class="col text-right label label-info">
                    @if ($message->created_at != $message->updated_at)
                        Обновлено: {{ $message->updated_at }}
                    @else
                        Изменений не было.
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection